"""Opens a pull request with what a finished run produced.

The only component that writes outside the platform's own boundary, which
is why it is a separate Lambda rather than a route on `λ api`: its role
carries exactly three permissions -- read the GitHub token, read the run,
read that run's workspace -- and nothing else. It cannot start executions,
cannot write to DynamoDB, and cannot reach any other bucket prefix.

It is never invoked by the state machine. A human asks for it from the UI
once they have read the report, so publishing stays a decision rather than
a side effect of a run finishing.
"""

from __future__ import annotations

import json
import os
from typing import Any

GITHUB_API = "https://api.github.com"
GITHUB_TOKEN_SECRET_ARN_ENV = "GITHUB_TOKEN_SECRET_ARN"
WORKSPACE_BUCKET_ENV = "MODHUB_WORKSPACE_BUCKET"
WORKING_VERSION = "v1"

PUBLISHABLE_STATES = {"LISTO_PARA_REVISION", "COMPLETADO_PARCIALMENTE"}


class PullRequestError(Exception):
    pass


def _response(status: int, payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusCode": status,
        "headers": {"Content-Type": "application/json"},
        "body": json.dumps(payload, default=str),
    }


def _requested_by(event: dict[str, Any]) -> str:
    claims = (
        event.get("requestContext", {}).get("authorizer", {}).get("jwt", {}).get("claims", {})
    )
    return claims.get("sub") or (event.get("headers") or {}).get("x-requested-by") or "anonymous"


def _workspace_files(s3_resource: Any, bucket: str, run_id: str, paths: list[str]) -> dict[str, bytes]:
    prefix = f"ws/{run_id}/{WORKING_VERSION}/"
    files: dict[str, bytes] = {}
    for path in paths:
        obj = s3_resource.Object(bucket, f"{prefix}{path}")
        files[path] = obj.get()["Body"].read()
    return files


class GitHub:
    def __init__(self, token: str, session: Any) -> None:
        self._session = session
        self._headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    def _request(self, method: str, path: str, **kwargs: Any) -> Any:
        response = self._session.request(
            method, f"{GITHUB_API}{path}", headers=self._headers, timeout=30, **kwargs
        )
        if response.status_code >= 400:
            raise PullRequestError(f"{method} {path} -> {response.status_code}: {response.text[:300]}")
        return response.json() if response.text else {}

    def default_branch(self, repo: str) -> str:
        return self._request("GET", f"/repos/{repo}")["default_branch"]

    def create_branch(self, repo: str, branch: str, from_sha: str) -> None:
        self._request(
            "POST",
            f"/repos/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch}", "sha": from_sha},
        )

    def put_file(self, repo: str, branch: str, path: str, content: bytes, message: str) -> None:
        import base64

        existing = self._session.get(
            f"{GITHUB_API}/repos/{repo}/contents/{path}",
            headers=self._headers,
            params={"ref": branch},
            timeout=30,
        )
        body: dict[str, Any] = {
            "message": message,
            "content": base64.b64encode(content).decode("ascii"),
            "branch": branch,
        }
        if existing.status_code == 200:
            body["sha"] = existing.json()["sha"]
        self._request("PUT", f"/repos/{repo}/contents/{path}", json=body)

    def open_pull_request(self, repo: str, branch: str, base: str, title: str, body: str) -> str:
        created = self._request(
            "POST",
            f"/repos/{repo}/pulls",
            json={"title": title, "head": branch, "base": base, "body": body},
        )
        return created["html_url"]


def _pr_body(run: dict[str, Any]) -> str:
    plan = run.get("plan") or {}
    sources = "\n".join(f"- {s}" for s in plan.get("sources") or []) or "- (none recorded)"
    return (
        f"Generated by the Engineering Modernization Hub.\n\n"
        f"**Objective:** {run.get('objetivo')}\n"
        f"**Strategy:** {run.get('strategy_id')} {run.get('strategy_version')}\n"
        f"**Verdict:** {run.get('status')} "
        f"(${run.get('spent_usd')} of ${run.get('max_usd')})\n"
        f"**plan_hash:** `{run.get('plan_hash')}`\n\n"
        f"### Summary\n{plan.get('summary', '')}\n\n"
        f"### Sources consulted\n{sources}\n\n"
        f"---\n"
        f"The verdict above was computed from the real test suite by a component that "
        f"never calls a model. Review the diff as you would any other pull request."
    )


def open_pull_request(
    event: dict[str, Any], runs_table: Any, s3_resource: Any, secrets_client: Any, session: Any
) -> dict[str, Any]:
    run_id = (event.get("pathParameters") or {}).get("run_id")
    if not run_id:
        return _response(400, {"code": "MISSING_RUN_ID", "message": "run_id is required."})

    run = runs_table.get(run_id)
    if run is None:
        return _response(404, {"code": "RUN_NOT_FOUND", "message": "No run with that id.", "run_id": run_id})

    run_data = run.model_dump(mode="json")

    if run_data["status"] not in PUBLISHABLE_STATES:
        return _response(
            409,
            {
                "code": "RUN_NOT_PUBLISHABLE",
                "message": f"A run in {run_data['status']} has nothing to publish.",
                "run_id": run_id,
            },
        )

    requester = _requested_by(event)
    if requester != run_data["requested_by"]:
        return _response(
            403,
            {"code": "NOT_REQUESTER", "message": "Only the requester can publish this run.", "run_id": run_id},
        )

    changed = run_data.get("changed_paths") or []
    if not changed:
        return _response(
            409,
            {"code": "NO_CHANGES", "message": "This run changed no files.", "run_id": run_id},
        )

    token = secrets_client.get_secret_value(SecretId=os.environ[GITHUB_TOKEN_SECRET_ARN_ENV])["SecretString"]
    files = _workspace_files(s3_resource, os.environ[WORKSPACE_BUCKET_ENV], run_id, changed)

    github = GitHub(token, session)
    repo = run_data["repo"]
    branch = f"modhub/{run_id[:8]}"

    try:
        base = github.default_branch(repo)
        github.create_branch(repo, branch, run_data["commit"])
        for path, content in files.items():
            github.put_file(repo, branch, path, content, f"modhub: {run_data['objetivo'][:60]}")
        url = github.open_pull_request(
            repo,
            branch,
            base,
            f"Modernization: {run_data['objetivo'][:70]}",
            _pr_body(run_data),
        )
    except PullRequestError as exc:
        return _response(502, {"code": "GITHUB_ERROR", "message": str(exc), "run_id": run_id})

    return _response(201, {"run_id": run_id, "pull_request_url": url, "branch": branch})


def handler(event: dict[str, Any], context: Any = None) -> dict[str, Any]:
    import boto3
    import requests

    from core_py.persistence import RunsTable

    return open_pull_request(
        event,
        RunsTable(resource=boto3.resource("dynamodb")),
        boto3.resource("s3"),
        boto3.client("secretsmanager"),
        requests.Session(),
    )
